export { getAll } from "./getAll";
export { create } from "./create";
export { getFromId } from "./getFromId";
export { remove } from "./remove";
export { getOwnQuizzes } from "./getOwnQuizzes";
export { getFollowedQuizzes } from "./getFollowedQuizzes";
export { addToFollowedQuizzes } from "./addToFollowedQuizzes";
export { addToOwnQuizzes } from "./addToOwnQuizzes";
export { removeFromFollowedQuizzes } from "./removeFromFollowedQuizzes";
