import { UserRole } from "@prisma/client";

export enum PERMISSIONS {
	//SUPER ADMIN
	USERS_READ = "USERS_READ",
	USERS_DELETE = "USERS_DELETE",

	QUIZ_EDIT_ANY = "QUIZ_EDIT_ANY",
	QUIZ_DELETE_ANY = "QUIZ_DELETE_ANY",

	//APPLICATION USER
	QUIZ_FOLLOW_ANY = "QUIZ_FOLLOW_ANY",

	QUIZ_RATE_ANY = "QUIZ_RATE_ANY",

	QUIZ_CREATE_OWN = "QUIZ_CREATE_OWN",
	QUIZ_READ_ALL = "QUIZ_READ_ALL",
	QUIZ_EDIT_OWN = "QUIZ_EDIT_OWN",
	QUIZ_DELETE_OWN = "QUIZ_DELETE_OWN",
}

export const ROLE_PERMISSIONS: Record<UserRole, PERMISSIONS[]> = {
	SUPER_ADMIN: Object.values(PERMISSIONS),
	APPLICATION_USER: [
		PERMISSIONS.QUIZ_FOLLOW_ANY,
		PERMISSIONS.QUIZ_RATE_ANY,
		PERMISSIONS.QUIZ_CREATE_OWN,
		PERMISSIONS.QUIZ_READ_ALL,
		PERMISSIONS.QUIZ_EDIT_OWN,
		PERMISSIONS.QUIZ_DELETE_OWN,
	],
};
