name: Deploy to Render

on:
  push:
    branches: ["api"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: # Required if github_deployment is set to true.
      deployments: write
    steps:
      - uses: actions/checkout@v3
      - uses: JorgeLNJunior/render-deploy@v1.4.2
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }} # required
          api_key: ${{ secrets.RENDER_API_KEY }} # required
          github_token:
