version: "3.8"
services:
  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: whirl_db
    ports:
      - "5555:5432"
    volumes:
      - db:/var/lib/postgresql

volumes:
  db:
