name: Deploy API to Render

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: ./api

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: # Required if github_deployment is set to true.
      deployments: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          path: api

      - uses: JorgeLNJunior/render-deploy@v1.4.2
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }} # required
          api_key: ${{ secrets.RENDER_API_KEY }} # required
          github_token: ${{ secrets.GITHUB_TOKEN }}
